version: '3.9'
services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID : ${UID}
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    volumes:
      - ".:/mnt:rw,z"
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
